# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


import cv2, datetime, threading

width = 100
height = 100
path = "./"
binarization = False
vol = 0


class Thread(QThread):
    changePixmap = pyqtSignal(QImage)
    frame = None
    saveFrame = None
    x, y = int(640/2), int(480/2)

    def run(self):
        global path
        global width
        global height
        global binarization
        global vol

        cap = cv2.VideoCapture(0)
        while True:

            ret, self.frame = cap.read()
            ret, self.saveFrame = cap.read()

            if binarization:
                self.frame = cv2.cvtColor(self.frame, cv2.COLOR_BGR2GRAY)
                self.saveFrame = cv2.cvtColor(self.saveFrame, cv2.COLOR_BGR2GRAY)

                ret, self.frame = cv2.threshold(self.frame, vol, 255, cv2.THRESH_BINARY)                
                ret, self.saveFrame = cv2.threshold(self.saveFrame, vol, 255, cv2.THRESH_BINARY)

            
            cv2.rectangle( self.frame, ( self.x - width, self.y - height ), ( self.x+width, self.y+height), (255, 255, 255), 3 )

            if ret:
                # QLable에 맞게 변환
                # https://stackoverflow.com/a/55468544/6622587
                rgbImage = cv2.cvtColor(self.frame, cv2.COLOR_BGR2RGB)
                h, w, ch = rgbImage.shape
                bytesPerLine = ch * w
                convertToQtFormat = QImage(rgbImage.data, w, h, bytesPerLine, QImage.Format_RGB888)
                p = convertToQtFormat.scaled(640, 480, Qt.KeepAspectRatio)
                self.changePixmap.emit(p)

    def capture(self, path):

        global width
        global height

        date = datetime.datetime.now().strftime('%Y-%d-%m %H_%M_%S.%f')
        fname = path + '/' + date + '.jpg'
        print('capture:', fname)

        self.saveFrame =  self.saveFrame[ self.y-height:self.y+height, self.x-width:self.x+width ]

        cv2.imwrite(fname, self.saveFrame)


class Ui_Form(object):

    th = None

    def setImage(self, image):
        self.pictureBox.setPixmap(QPixmap.fromImage(image))
        self.pictureBox.setStyleSheet('QLabel{ }')


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(682, 574)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pictureBox = QtWidgets.QLabel(Form)
        self.pictureBox.setStyleSheet("QLabel{\n"
"background: rgb(180, 180, 180)\n"
"}")
        self.pictureBox.setText("")
        self.pictureBox.setObjectName("pictureBox")
        self.gridLayout.addWidget(self.pictureBox, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setRange( 10, 240 )
        self.horizontalSlider.setValue(100)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setRange(10, 320)
        self.horizontalSlider_2.setValue(100)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setEnabled(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setEnabled(True)
        self.checkBox.setText('binarization')
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBox)

        self.horizontalSlider_3 = QtWidgets.QSlider(Form)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider")
        self.horizontalSlider_3.setRange( 0, 255 )
        self.horizontalSlider_3.setValue(0)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_3)        

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.selectDirectoryPath) # type: ignore
        self.pushButton.clicked.connect(self.capture) # type: ignore
        self.horizontalSlider.valueChanged[int].connect(self.setHeight)
        self.horizontalSlider_2.valueChanged[int].connect(self.setWidth)
        self.horizontalSlider_3.valueChanged[int].connect(self.binarizationVol)

        self.checkBox.clicked.connect(self.binarization)



        QtCore.QMetaObject.connectSlotsByName(Form)

        self.th = Thread(Form)
        self.th.changePixmap.connect(self.setImage)
        self.th.start()        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "objectCapture"))
        self.pushButton_2.setText(_translate("Form", ".."))
        self.label.setText(_translate("Form", "options"))
        self.label_2.setText(_translate("Form", "Height"))
        self.label_3.setText(_translate("Form", "Width"))
        self.pushButton.setText(_translate("Form", "Capture(F12)"))
        self.pushButton.setShortcut(_translate("Form", "F12"))


    def selectDirectoryPath_thread(self):
        global path
        path = QFileDialog.getExistingDirectory()
        print(path)
        self.lineEdit.setText(path)

    def selectDirectoryPath(self):
        t = threading.Thread(target=self.selectDirectoryPath_thread)
        
        t.start()

    def binarization(self):
        global binarization
        if self.checkBox.isChecked():
            binarization = True
        else:
            binarization = False

    def binarizationVol(self, value):
        global vol
        vol = value

    def capture(self):
        global path
        self.th.capture(path)

    def setWidth(self, value):
        global width
        width = value
        print( 'width:', value )
    
    def setHeight(self, value):
        global height
        height = value
        print( 'height:', value )




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
